{
    "openapi": "3.0.0",
    "info": {
        "title": "RentX Documentation",
        "description": "This is an API Rent",
        "version": "1.0.0",
        "contact": {
            "email": "dani@rocketseat.com.br"
        }
    },
    "paths": {
        "/sessions": {
            "post": {
                "tags": [
                    "Session"
                ],
                "summary": "Authentication user",
                "description": "Authenticate a user on the platform",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "email": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    }
                                },
                                "example": {
                                    "email": "user@email.com.br",
                                    "password": "pass123"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "token": {
                                            "type": "string"
                                        },
                                        "user": {
                                            "type": "object"
                                        },
                                        "refresh_token": {
                                            "type": "object"
                                        }
                                    }
                                },
                                "examples": {
                                    "Successfully authorized": {
                                        "value": {
                                            "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6I",
                                            "user": {
                                                "name": "User name",
                                                "email": "user@email.com.br"
                                            },
                                            "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Email or password incorrect",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        }
                                    }
                                },
                                "examples": {
                                    "Incorrect Credentials": {
                                        "value": {
                                            "message": "Email or password incorrect"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/refresh-token": {
            "post": {
                "tags": [
                    "Session"
                ],
                "summary": "Refresh token",
                "description": "Renewing a user's access by requesting a new token",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "token": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "token": {
                                            "type": "string"
                                        },
                                        "refresh_token": {
                                            "type": "object"
                                        }
                                    }
                                },
                                "examples": {
                                    "New generated token": {
                                        "value": {
                                            "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6I",
                                            "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "$ref": "#/components/responses/InvalidToken"
                    }
                }
            }
        },
        "/users": {
            "post": {
                "tags": [
                    "Account"
                ],
                "summary": "Authentication user",
                "description": "Account creation on the platform",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "type": "string"
                                    },
                                    "email": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    },
                                    "driver_license": {
                                        "type": "string"
                                    }
                                },
                                "example": {
                                    "name": "User Name",
                                    "email": "user@email.com.br",
                                    "password": "pass123",
                                    "driver_license": "ABC-123"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "User Created Successfully"
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        }
                                    }
                                },
                                "examples": {
                                    "Incorrect Credentials": {
                                        "value": {
                                            "message": "Email or password incorrect"
                                        }
                                    },
                                    "E-mail already registered": {
                                        "value": {
                                            "message": "User already exists"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/users/avatar": {
            "patch": {
                "tags": [
                    "Account"
                ],
                "summary": "Upload Avatar",
                "description": "Upload a profile picture",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "avatar": {
                                        "type": "string",
                                        "format": "binary"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "204": {
                        "description": "Avatar sent"
                    },
                    "401": {
                        "$ref": "#/components/responses/Unauthorized"
                    }
                }
            }
        },
        "/password/forgot": {
            "post": {
                "tags": [
                    "Account"
                ],
                "summary": "Recover password",
                "description": "Send email for password recovery",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "email": {
                                        "type": "string"
                                    }
                                },
                                "example": {
                                    "email": "user@email.com.br"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Recovery email sent"
                    },
                    "400": {
                        "description": "Email not sent",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        }
                                    }
                                },
                                "examples": {
                                    "User not found": {
                                        "value": {
                                            "message": "User does not exists"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/categories": {
            "post": {
                "tags": [
                    "Category"
                ],
                "summary": "Create a category",
                "description": "Create a new category",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "type": "string"
                                    },
                                    "description": {
                                        "type": "string"
                                    }
                                },
                                "example": {
                                    "name": "category name sample",
                                    "description": "Category description sample"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        }
                                    }
                                },
                                "examples": {
                                    "Category already exists": {
                                        "value": {
                                            "message": "Category already exists"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "$ref": "#/components/responses/Unauthorized"
                    }
                }
            },
            "get": {
                "tags": [
                    "Category"
                ],
                "summary": "List all categories",
                "description": "List all categories",
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "name": {
                                                "type": "string"
                                            },
                                            "description": {
                                                "type": "string"
                                            }
                                        },
                                        "example": {
                                            "id": "1421278d-b2a5-49b1-8c77-ec48ad10368a",
                                            "name": "Category name",
                                            "description": "Category Description",
                                            "created_at": "2022-12-21T14:28:52.349Z"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "$ref": "#/components/responses/InvalidToken"
                    }
                }
            }
        },
        "/categories/import": {
            "post": {
                "tags": [
                    "Category"
                ],
                "summary": "Upload a new category",
                "description": "Upload a new category",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "file": {
                                        "type": "string",
                                        "format": "binary"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "401": {
                        "$ref": "#/components/responses/Unauthorized"
                    }
                }
            }
        },
        "/specifications": {
            "post": {
                "tags": [
                    "Specifications"
                ],
                "summary": "Create a specification",
                "description": "Create a new specification",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/definitions/Specification"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Specification already exists"
                    },
                    "401": {
                        "$ref": "#/components/responses/Unauthorized"
                    }
                }
            },
            "get": {
                "tags": [
                    "Specifications"
                ],
                "summary": "List all specifications",
                "description": "List all specifications",
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "name": {
                                                "type": "string"
                                            },
                                            "description": {
                                                "type": "string"
                                            }
                                        },
                                        "example": {
                                            "id": "1421278d-b2a5-49b1-8c77-ec48ad10368a",
                                            "name": "Specification name",
                                            "description": "Specification Description",
                                            "created_at": "2022-12-21T14:28:52.349Z"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "$ref": "#/components/responses/InvalidToken"
                    }
                }
            }
        },
        "/cars": {
            "post": {
                "tags": [
                    "Cars"
                ],
                "summary": "Create a new car",
                "description": "Create a new car",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/definitions/Car"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Car already exists"
                    },
                    "401": {
                        "$ref": "#/components/responses/Unauthorized"
                    }
                }
            },
            "get": {
                "tags": [
                    "Cars"
                ],
                "summary": "List all cars",
                "description": "List all cars",
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "id": {
                                                "type": "string"
                                            },
                                            "available": {
                                                "type": "boolean"
                                            },
                                            "name": {
                                                "type": "string"
                                            },
                                            "description": {
                                                "type": "string"
                                            },
                                            "daily_rate": {
                                                "type": "number"
                                            },
                                            "license_plate": {
                                                "type": "string"
                                            },
                                            "fine_amount": {
                                                "type": "number"
                                            },
                                            "brand": {
                                                "type": "string"
                                            },
                                            "category_id": {
                                                "type": "string"
                                            },
                                            "created_at": {
                                                "type": "date"
                                            },
                                            "images": {
                                                "type": "array",
                                                "items": {
                                                    "type": "object",
                                                    "properties": {
                                                        "id": {
                                                            "type": "string"
                                                        },
                                                        "car_id": {
                                                            "type": "string"
                                                        },
                                                        "image_name": {
                                                            "type": "string"
                                                        },
                                                        "created_at": {
                                                            "type": "date"
                                                        }
                                                    }
                                                }
                                            }
                                        },
                                        "example": {
                                            "name": "Car Name",
                                            "description": "Car Description",
                                            "daily_rate": 100,
                                            "license_plate": "ABC123",
                                            "fine_amount": 123,
                                            "brand": "BHG",
                                            "category_id": "123213-3123-231231",
                                            "created_at": "2020-08-01T00:00:00Z",
                                            "images": [
                                                {
                                                    "id": "ad19c01f-b47a-4f29-a06a-6bfa52a93a97",
                                                    "car_id": "767b5b31-25bb-452f-9a9f-2f7ac9a7de85",
                                                    "image_name": "332ec8d598c7f3af85f94f305a365436-photo2.jpg",
                                                    "created_at": "2022-12-26T19:54:49.563Z"
                                                }
                                            ]
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "$ref": "#/components/responses/InvalidToken"
                    }
                }
            }
        },
        "/cars/specifications/{id}": {
            "post": {
                "tags": [
                    "Cars"
                ],
                "summary": "Attribute specifications on cars",
                "description": "Attribute specifications on cars",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Car id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "type": "string",
                                "properties": {
                                    "specifications_id": {
                                        "type": "array",
                                        "items": {
                                            "type": "string"
                                        }
                                    }
                                },
                                "example": {
                                    "specifications_id": [
                                        "25219933-c921-4d08-a5bd-bf633607742f"
                                    ]
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "401": {
                        "$ref": "#/components/responses/Unauthorized"
                    }
                }
            }
        },
        "/cars/images/{id}": {
            "post": {
                "tags": [
                    "Cars"
                ],
                "summary": "Upload images",
                "description": "Upload images",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Car id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "images": {
                                        "type": "array",
                                        "items": {
                                            "type": "string",
                                            "format": "binary"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "401": {
                        "$ref": "#/components/responses/Unauthorized"
                    }
                }
            }
        },
        "/rentals": {
            "post": {
                "tags": [
                    "Rentals"
                ],
                "summary": "Make a rent",
                "description": "Make a rent",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "car_id": {
                                        "type": "string"
                                    },
                                    "expected_return_date": {
                                        "type": "string"
                                    }
                                },
                                "examples": {
                                    "car_id": "767b5b31-25bb-452f-9a9f-2f7ac9a7de85",
                                    "expected_return_date": "2022-12-29T19:59:46.997Z"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        }
                                    }
                                },
                                "examples": {
                                    "Car does not exist": {
                                        "value": {
                                            "message": "Car does not exist"
                                        }
                                    },
                                    "Car is unavailable": {
                                        "value": {
                                            "message": "Car is unavailable"
                                        }
                                    },
                                    "Invalid return time": {
                                        "value": {
                                            "message": "Invalid return time"
                                        }
                                    },
                                    "There's a rental in progress for user": {
                                        "value": {
                                            "message": "There's a rental in progress for user"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "$ref": "#/components/responses/InvalidToken"
                    }
                }
            },
            "get": {
                "tags": [
                    "Rentals"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "summary": "List all rentals",
                "description": "List all rentals",
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "id": {
                                                "type": "string"
                                            },
                                            "car_id": {
                                                "type": "string"
                                            },
                                            "user_id": {
                                                "type": "string"
                                            },
                                            "start_date": {
                                                "type": "date"
                                            },
                                            "end_date": {
                                                "type": "date"
                                            },
                                            "expected_return_date": {
                                                "type": "date"
                                            },
                                            "total": {
                                                "type": "number"
                                            },
                                            "created_at": {
                                                "type": "date"
                                            },
                                            "updated_at": {
                                                "type": "date"
                                            },
                                            "car": {
                                                "type": "object",
                                                "properties": {
                                                    "id": {
                                                        "type": "string"
                                                    },
                                                    "available": {
                                                        "type": "boolean"
                                                    },
                                                    "name": {
                                                        "type": "string"
                                                    },
                                                    "description": {
                                                        "type": "string"
                                                    },
                                                    "daily_rate": {
                                                        "type": "number"
                                                    },
                                                    "license_plate": {
                                                        "type": "string"
                                                    },
                                                    "fine_amount": {
                                                        "type": "number"
                                                    },
                                                    "brand": {
                                                        "type": "string"
                                                    },
                                                    "category_id": {
                                                        "type": "string"
                                                    },
                                                    "created_at": {
                                                        "type": "date"
                                                    }
                                                }
                                            }
                                        },
                                        "example": {
                                            "id": "0c5b9bf6-ecd8-4694-8aaf-89a93dab12cf",
                                            "car_id": "767b5b31-25bb-452f-9a9f-2f7ac9a7de85",
                                            "user_id": "69105fb7-8331-470f-8d94-3e036f49bae6",
                                            "start_date": "2022-12-26T20:28:37.899Z",
                                            "end_date": null,
                                            "expected_return_date": "2022-12-29T19:59:46.997Z",
                                            "total": null,
                                            "created_at": "2022-12-26T20:28:37.899Z",
                                            "updated_at": "2022-12-26T20:28:37.899Z",
                                            "car": {
                                                "id": "767b5b31-25bb-452f-9a9f-2f7ac9a7de85",
                                                "available": false,
                                                "name": "BMW i8",
                                                "description": "Carro híbrido de alta performance",
                                                "daily_rate": 1000,
                                                "license_plate": "ABC-1235",
                                                "fine_amount": 600,
                                                "brand": "BMW",
                                                "category_id": "1421278d-b2a5-49b1-8c77-ec48ad10368a",
                                                "created_at": "2022-12-26T16:54:19.624Z"
                                            }
                                        }
                                    }
                                }
                            }
                        },
                        "401": {
                            "$ref": "#/components/responses/InvalidToken"
                        }
                    }
                }
            }
        },
        "/rentals/devolution/{id}": {
            "post": {
                "tags": [
                    "Rentals"
                ],
                "summary": "Return the rental car",
                "description": "Return the rental car",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Rental id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "images": {
                                        "type": "array",
                                        "items": {
                                            "type": "string",
                                            "format": "binary"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Returned car"
                    },
                    "404": {
                        "description": "Rental does not exist"
                    },
                    "401": {
                        "$ref": "#/components/responses/InvalidToken"
                    }
                }
            }
        }
    },
    "definitions": {
        "Specification": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                }
            },
            "example": {
                "name": "Specification Name",
                "description": "Specification Description"
            }
        },
        "Car": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "daily_rate": {
                    "type": "number"
                },
                "license_plate": {
                    "type": "string"
                },
                "fine_amount": {
                    "type": "number"
                },
                "brand": {
                    "type": "string"
                },
                "category_id": {
                    "type": "string"
                }
            },
            "example": {
                "name": "Car Name",
                "description": "Car Description",
                "daily_rate": 100,
                "license_plate": "ABC123",
                "fine_amount": 123,
                "brand": "BHG",
                "category_id": "123213-3123-231231"
            }
        }
    },
    "components": {
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        },
        "responses": {
            "Unauthorized": {
                "description": "Not authorized",
                "content": {
                    "application/json": {
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {
                                    "type": "string"
                                }
                            }
                        },
                        "examples": {
                            "User isn't admin": {
                                "value": {
                                    "message": "User isn't admin"
                                }
                            },
                            "Invalid Token": {
                                "value": {
                                    "message": "Invalid Token"
                                }
                            }
                        }
                    }
                }
            },
            "InvalidToken": {
                "description": "Not authorized",
                "content": {
                    "application/json": {
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {
                                    "type": "string"
                                }
                            }
                        },
                        "examples": {
                            "Invalid Token": {
                                "value": {
                                    "message": "Invalid Token"
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}